version: '3.8'

services:
  sftp:
    image: atmoz/sftp
    ports:
      - "2222:22"
    volumes:
      - ./sftp-data:/home/user/upload
    environment:
      SFTP_USERS: "user:password:1001" # Format: user:pass:uid

volumes:
  sftp-data:
